name: CI-auth

on:
  push:
    branches:
      - master
    # paths:
      # - 'apps/auth/**'

  pull_request:
    branches:
      - master
    # paths:
      # - 'apps/auth/**'

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci 

      - name: run lint
        run: npm run lint

  test:
    name: run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: run unit test
        run: npm run test