name: CI-billing

on:
  push:
    branches: [develop, master]
    paths:
      - 'apps/billing/**'

  pull_request:
    branches: [develop, master]
    paths:
      - 'apps/billing/**'

jobs:
  test:
    name: Run lint and unit test  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-key: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci 

      - name: run lint
        run: npm run lint

      - name: run unit test
        run: npm run test:cov

      - name: Upload test coverage
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage
      
      - uses: actions/download-artifact@v2

      - name: Create a release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' 
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage reports
        uses: codecov/codecov-action@v2
        with: 
          token: ${{ secrets.CODECOVE_TOKEN }}
          files: ./coverage/clover.xml
          flags: unittest
          name: codecov-umbrella
